export enum Subject {
  FRENCH = 'FRENCH',
  MATHEMATICS = 'MATHEMATICS',
  SPORT = 'SPORT',
  ART = 'ART',
  MUSIC = 'MUSIC',
  ASK_THE_WORLD = 'ASK_THE_WORLD',
  MODERN_LANGUAGE = 'MODERN_LANGUAGE',
  CIVIC_EDUCATION = 'CIVIC_EDUCATION '
}
